apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: sei-k8s-controller
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
      app.kubernetes.io/name: sei-k8s-controller
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
        app.kubernetes.io/name: sei-k8s-controller
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - command:
        - /manager
        args:
          - --metrics-bind-address=:8443
          - --leader-elect
          - --health-probe-bind-address=:8081
        image: 189176372795.dkr.ecr.us-east-2.amazonaws.com/sei/sei-k8s-controller@sha256:95d9d0a74d8b3a27f7991040305ea32f72cfd8a63c5413be14742378861137c4
        name: manager
        env:
          - name: SEI_NODEPOOL_NAME
            value: sei-node
          - name: SEI_TOLERATION_KEY
            value: sei.io/workload
          - name: SEI_TOLERATION_VALUE
            value: sei-node
          - name: SEI_SERVICE_ACCOUNT
            value: seid-node
          - name: SEI_STORAGE_CLASS_PERF
            value: gp3-10k-750
          - name: SEI_STORAGE_CLASS_DEFAULT
            value: gp3
          - name: SEI_STORAGE_SIZE_DEFAULT
            value: 1000Gi
          - name: SEI_STORAGE_SIZE_ARCHIVE
            value: 2000Gi
          - name: SEI_RESOURCE_CPU_ARCHIVE
            value: "8"
          - name: SEI_RESOURCE_MEM_ARCHIVE
            value: 48Gi
          - name: SEI_RESOURCE_CPU_DEFAULT
            value: "4"
          - name: SEI_RESOURCE_MEM_DEFAULT
            value: 32Gi
          - name: SEI_SNAPSHOT_REGION
            value: eu-central-1
          - name: SEI_CONTROLLER_SA_PRINCIPAL
            value: "cluster.local/ns/sei-k8s-controller-system/sa/sei-k8s-controller-manager"
        ports: []
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
        volumeMounts: []
      volumes: []
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
