apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: sei-k8s-controller
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
      app.kubernetes.io/name: sei-k8s-controller
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
        app.kubernetes.io/name: sei-k8s-controller
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - command:
        - /manager
        args:
          - --metrics-bind-address=:8080
          - --leader-elect
          - --health-probe-bind-address=:8081
        image: 189176372795.dkr.ecr.us-east-2.amazonaws.com/sei/sei-k8s-controller:98833f18e5baad7f4d898629b6a3e2f29de3dd1b
        name: manager
        env:
          - name: SEI_NODEPOOL_NAME
            value: sei-node
          - name: SEI_TOLERATION_KEY
            value: sei.io/workload
          - name: SEI_TOLERATION_VALUE
            value: sei-node
          - name: SEI_SERVICE_ACCOUNT
            value: seid-node
          - name: SEI_STORAGE_CLASS_PERF
            value: gp3-10k-750
          - name: SEI_STORAGE_CLASS_DEFAULT
            value: gp3
          - name: SEI_STORAGE_SIZE_DEFAULT
            value: 2000Gi
          - name: SEI_STORAGE_SIZE_ARCHIVE
            value: 4000Gi
          - name: SEI_RESOURCE_CPU_ARCHIVE
            value: "16"
          - name: SEI_RESOURCE_MEM_ARCHIVE
            value: 256Gi
          - name: SEI_RESOURCE_CPU_DEFAULT
            value: "4"
          - name: SEI_RESOURCE_MEM_DEFAULT
            value: 32Gi
          - name: SEI_SNAPSHOT_BUCKET
            value: dev-sei-snapshots
          - name: SEI_SNAPSHOT_REGION
            value: us-east-2
          - name: SEI_RESULT_EXPORT_BUCKET
            value: dev-sei-shadow-results
          - name: SEI_RESULT_EXPORT_REGION
            value: us-east-2
          - name: SEI_RESULT_EXPORT_PREFIX
            value: shadow-results/
          - name: SEI_GENESIS_BUCKET
            value: dev-sei-k8s-genesis-artifacts
          - name: SEI_GENESIS_REGION
            value: us-east-2
          - name: SEI_CONTROLLER_SA_PRINCIPAL
            value: "cluster.local/ns/sei-k8s-controller-system/sa/sei-k8s-controller-manager"
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        - containerPort: 8081
          name: health
          protocol: TCP
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
        volumeMounts: []
      volumes: []
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
