apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  # Replace with the EFS filesystem ID from AWS (e.g. fs-0123456789abcdef0)
  fileSystemId: "fs-0197eb4ce202ae165"
  directoryPerms: "700"
reclaimPolicy: Retain
volumeBindingMode: Immediate
