---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumes
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - chaos-mesh.org
  resources:
  - workflownodes
  - workflows
  verbs:
  - get
  - list
- apiGroups:
  - sei.io
  resources:
  - seinetworks
  - seinodes
  - seinodetasks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sei.io
  resources:
  - seinetworks/finalizers
  - seinodes/finalizers
  - seinodetasks/finalizers
  verbs:
  - update
- apiGroups:
  - sei.io
  resources:
  - seinetworks/status
  - seinodes/status
  - seinodetasks/status
  verbs:
  - get
  - patch
  - update
