apiVersion: sei.io/v1alpha1
kind: SeiNode
metadata:
  name: atlantic-2-snapshotter
  namespace: default
spec:
  chainId: atlantic-2
  image: 189176372795.dkr.ecr.us-east-2.amazonaws.com/sei/sei-chain:76f70dd418861906135434e36930e8ca99d78700
  entrypoint:
    command: ["seid"]
    args: ["start", "--home", "/sei"]
  genesis:
    chainId: atlantic-2
    s3:
      uri: s3://sei-testnet-genesis-config/atlantic-2/genesis.json
      region: us-east-2
  peers:
    sources:
      - ec2Tags:
          region: eu-central-1
          tags:
            ChainIdentifier: atlantic-2
            Component: snapshotter
  storage:
    retainOnDelete: true
  sidecar:
    image: 189176372795.dkr.ecr.us-east-2.amazonaws.com/sei-sidecar:latest
  snapshotGeneration:
    interval: 2000
    keepRecent: 5
    destination:
      s3:
        bucket: atlantic-2-snapshots
        prefix: state-sync
        region: eu-central-1
