apiVersion: sei.sei.io/v1alpha1
kind: SeiNodePool
metadata:
  labels:
    app.kubernetes.io/name: platform
    app.kubernetes.io/managed-by: kustomize
  name: devnet-hetero
spec:
  nodeConfigurations:
    - name: validator-0
      image: ghcr.io/sei-protocol/sei-box:v1.0.0
      entrypoint:
        command: ["sei-box"]
        args: ["start", "--mode=validator"]
    - name: archive-0
      image: ghcr.io/sei-protocol/sei-box:v2.0.0
      entrypoint:
        command: ["sei-box"]
        args: ["start", "--mode=archive"]
    - name: rpc-0
      image: ghcr.io/sei-protocol/sei-box:v1.0.0
      entrypoint:
        command: ["sei-box"]
        args: ["start", "--mode=rpc"]
  genesis:
    chainId: sei-hetero
    validators:
      - name: validator-0
        power: 100
  storage:
    size: "100Gi"
