apiVersion: sei.io/v1alpha1
kind: SeiNodePool
metadata:
  name: arctic-replay
spec:
  nodeConfigurations:
    - name: node-0
      image: 189176372795.dkr.ecr.us-east-2.amazonaws.com/sei/sei-chain:76f70dd418861906135434e36930e8ca99d78700
      entrypoint:
        command: ["seid"]
        args: ["start", "--chain-id", "arctic-1"]
  genesis:
    chainId: arctic-1
    stateSource:
      stateSync:
        bucket: pacific-1-snapshots
        prefix: state-sync/
        region: eu-central-1
        targetHeight: 0
  storage:
    size: 1000Gi
    storageClass: gp3
    retainOnDelete: true
