//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArchiveSpec) DeepCopyInto(out *ArchiveSpec) {
	*out = *in
	if in.Peers != nil {
		in, out := &in.Peers, &out.Peers
		*out = make([]PeerSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SnapshotGeneration != nil {
		in, out := &in.SnapshotGeneration, &out.SnapshotGeneration
		*out = new(SnapshotGenerationConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArchiveSpec.
func (in *ArchiveSpec) DeepCopy() *ArchiveSpec {
	if in == nil {
		return nil
	}
	out := new(ArchiveSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigDiagnostic) DeepCopyInto(out *ConfigDiagnostic) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigDiagnostic.
func (in *ConfigDiagnostic) DeepCopy() *ConfigDiagnostic {
	if in == nil {
		return nil
	}
	out := new(ConfigDiagnostic)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigStatus) DeepCopyInto(out *ConfigStatus) {
	*out = *in
	if in.Diagnostics != nil {
		in, out := &in.Diagnostics, &out.Diagnostics
		*out = make([]ConfigDiagnostic, len(*in))
		copy(*out, *in)
	}
	if in.LastValidatedAt != nil {
		in, out := &in.LastValidatedAt, &out.LastValidatedAt
		*out = (*in).DeepCopy()
	}
	if in.LastAppliedAt != nil {
		in, out := &in.LastAppliedAt, &out.LastAppliedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigStatus.
func (in *ConfigStatus) DeepCopy() *ConfigStatus {
	if in == nil {
		return nil
	}
	out := new(ConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EC2TagsPeerSource) DeepCopyInto(out *EC2TagsPeerSource) {
	*out = *in
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EC2TagsPeerSource.
func (in *EC2TagsPeerSource) DeepCopy() *EC2TagsPeerSource {
	if in == nil {
		return nil
	}
	out := new(EC2TagsPeerSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EntrypointConfig) DeepCopyInto(out *EntrypointConfig) {
	*out = *in
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EntrypointConfig.
func (in *EntrypointConfig) DeepCopy() *EntrypointConfig {
	if in == nil {
		return nil
	}
	out := new(EntrypointConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FullNodeSpec) DeepCopyInto(out *FullNodeSpec) {
	*out = *in
	if in.Peers != nil {
		in, out := &in.Peers, &out.Peers
		*out = make([]PeerSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Snapshot != nil {
		in, out := &in.Snapshot, &out.Snapshot
		*out = new(SnapshotSource)
		(*in).DeepCopyInto(*out)
	}
	if in.SnapshotGeneration != nil {
		in, out := &in.SnapshotGeneration, &out.SnapshotGeneration
		*out = new(SnapshotGenerationConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FullNodeSpec.
func (in *FullNodeSpec) DeepCopy() *FullNodeSpec {
	if in == nil {
		return nil
	}
	out := new(FullNodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenesisConfiguration) DeepCopyInto(out *GenesisConfiguration) {
	*out = *in
	if in.PVC != nil {
		in, out := &in.PVC, &out.PVC
		*out = new(GenesisPVCSource)
		**out = **in
	}
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(GenesisS3Source)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenesisConfiguration.
func (in *GenesisConfiguration) DeepCopy() *GenesisConfiguration {
	if in == nil {
		return nil
	}
	out := new(GenesisConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenesisPVCSource) DeepCopyInto(out *GenesisPVCSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenesisPVCSource.
func (in *GenesisPVCSource) DeepCopy() *GenesisPVCSource {
	if in == nil {
		return nil
	}
	out := new(GenesisPVCSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenesisS3Source) DeepCopyInto(out *GenesisS3Source) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenesisS3Source.
func (in *GenesisS3Source) DeepCopy() *GenesisS3Source {
	if in == nil {
		return nil
	}
	out := new(GenesisS3Source)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeConfiguration) DeepCopyInto(out *NodeConfiguration) {
	*out = *in
	in.Entrypoint.DeepCopyInto(&out.Entrypoint)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeConfiguration.
func (in *NodeConfiguration) DeepCopy() *NodeConfiguration {
	if in == nil {
		return nil
	}
	out := new(NodeConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeStatus) DeepCopyInto(out *NodeStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeStatus.
func (in *NodeStatus) DeepCopy() *NodeStatus {
	if in == nil {
		return nil
	}
	out := new(NodeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PeerSource) DeepCopyInto(out *PeerSource) {
	*out = *in
	if in.EC2Tags != nil {
		in, out := &in.EC2Tags, &out.EC2Tags
		*out = new(EC2TagsPeerSource)
		(*in).DeepCopyInto(*out)
	}
	if in.Static != nil {
		in, out := &in.Static, &out.Static
		*out = new(StaticPeerSource)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PeerSource.
func (in *PeerSource) DeepCopy() *PeerSource {
	if in == nil {
		return nil
	}
	out := new(PeerSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlannedTask) DeepCopyInto(out *PlannedTask) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlannedTask.
func (in *PlannedTask) DeepCopy() *PlannedTask {
	if in == nil {
		return nil
	}
	out := new(PlannedTask)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplayerSpec) DeepCopyInto(out *ReplayerSpec) {
	*out = *in
	if in.Peers != nil {
		in, out := &in.Peers, &out.Peers
		*out = make([]PeerSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Snapshot.DeepCopyInto(&out.Snapshot)
	if in.ResultExport != nil {
		in, out := &in.ResultExport, &out.ResultExport
		*out = new(ResultExportConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplayerSpec.
func (in *ReplayerSpec) DeepCopy() *ReplayerSpec {
	if in == nil {
		return nil
	}
	out := new(ReplayerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResultExportConfig) DeepCopyInto(out *ResultExportConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResultExportConfig.
func (in *ResultExportConfig) DeepCopy() *ResultExportConfig {
	if in == nil {
		return nil
	}
	out := new(ResultExportConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3SnapshotDestination) DeepCopyInto(out *S3SnapshotDestination) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3SnapshotDestination.
func (in *S3SnapshotDestination) DeepCopy() *S3SnapshotDestination {
	if in == nil {
		return nil
	}
	out := new(S3SnapshotDestination)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3SnapshotSource) DeepCopyInto(out *S3SnapshotSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3SnapshotSource.
func (in *S3SnapshotSource) DeepCopy() *S3SnapshotSource {
	if in == nil {
		return nil
	}
	out := new(S3SnapshotSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeiNode) DeepCopyInto(out *SeiNode) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeiNode.
func (in *SeiNode) DeepCopy() *SeiNode {
	if in == nil {
		return nil
	}
	out := new(SeiNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SeiNode) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeiNodeList) DeepCopyInto(out *SeiNodeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SeiNode, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeiNodeList.
func (in *SeiNodeList) DeepCopy() *SeiNodeList {
	if in == nil {
		return nil
	}
	out := new(SeiNodeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SeiNodeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeiNodePool) DeepCopyInto(out *SeiNodePool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeiNodePool.
func (in *SeiNodePool) DeepCopy() *SeiNodePool {
	if in == nil {
		return nil
	}
	out := new(SeiNodePool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SeiNodePool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeiNodePoolList) DeepCopyInto(out *SeiNodePoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SeiNodePool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeiNodePoolList.
func (in *SeiNodePoolList) DeepCopy() *SeiNodePoolList {
	if in == nil {
		return nil
	}
	out := new(SeiNodePoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SeiNodePoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeiNodePoolSpec) DeepCopyInto(out *SeiNodePoolSpec) {
	*out = *in
	in.NodeConfiguration.DeepCopyInto(&out.NodeConfiguration)
	out.Storage = in.Storage
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeiNodePoolSpec.
func (in *SeiNodePoolSpec) DeepCopy() *SeiNodePoolSpec {
	if in == nil {
		return nil
	}
	out := new(SeiNodePoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeiNodePoolStatus) DeepCopyInto(out *SeiNodePoolStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NodeStatuses != nil {
		in, out := &in.NodeStatuses, &out.NodeStatuses
		*out = make([]NodeStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeiNodePoolStatus.
func (in *SeiNodePoolStatus) DeepCopy() *SeiNodePoolStatus {
	if in == nil {
		return nil
	}
	out := new(SeiNodePoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeiNodeSpec) DeepCopyInto(out *SeiNodeSpec) {
	*out = *in
	if in.Entrypoint != nil {
		in, out := &in.Entrypoint, &out.Entrypoint
		*out = new(EntrypointConfig)
		(*in).DeepCopyInto(*out)
	}
	in.Genesis.DeepCopyInto(&out.Genesis)
	out.Storage = in.Storage
	if in.Overrides != nil {
		in, out := &in.Overrides, &out.Overrides
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Sidecar != nil {
		in, out := &in.Sidecar, &out.Sidecar
		*out = new(SidecarConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.FullNode != nil {
		in, out := &in.FullNode, &out.FullNode
		*out = new(FullNodeSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Archive != nil {
		in, out := &in.Archive, &out.Archive
		*out = new(ArchiveSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Replayer != nil {
		in, out := &in.Replayer, &out.Replayer
		*out = new(ReplayerSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Validator != nil {
		in, out := &in.Validator, &out.Validator
		*out = new(ValidatorSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeiNodeSpec.
func (in *SeiNodeSpec) DeepCopy() *SeiNodeSpec {
	if in == nil {
		return nil
	}
	out := new(SeiNodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeiNodeStatus) DeepCopyInto(out *SeiNodeStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PreInitPlan != nil {
		in, out := &in.PreInitPlan, &out.PreInitPlan
		*out = new(TaskPlan)
		(*in).DeepCopyInto(*out)
	}
	if in.InitPlan != nil {
		in, out := &in.InitPlan, &out.InitPlan
		*out = new(TaskPlan)
		(*in).DeepCopyInto(*out)
	}
	if in.ScheduledTasks != nil {
		in, out := &in.ScheduledTasks, &out.ScheduledTasks
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ConfigStatus != nil {
		in, out := &in.ConfigStatus, &out.ConfigStatus
		*out = new(ConfigStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeiNodeStatus.
func (in *SeiNodeStatus) DeepCopy() *SeiNodeStatus {
	if in == nil {
		return nil
	}
	out := new(SeiNodeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeiNodeStorageConfig) DeepCopyInto(out *SeiNodeStorageConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeiNodeStorageConfig.
func (in *SeiNodeStorageConfig) DeepCopy() *SeiNodeStorageConfig {
	if in == nil {
		return nil
	}
	out := new(SeiNodeStorageConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SidecarConfig) DeepCopyInto(out *SidecarConfig) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SidecarConfig.
func (in *SidecarConfig) DeepCopy() *SidecarConfig {
	if in == nil {
		return nil
	}
	out := new(SidecarConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotDestination) DeepCopyInto(out *SnapshotDestination) {
	*out = *in
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(S3SnapshotDestination)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotDestination.
func (in *SnapshotDestination) DeepCopy() *SnapshotDestination {
	if in == nil {
		return nil
	}
	out := new(SnapshotDestination)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotGenerationConfig) DeepCopyInto(out *SnapshotGenerationConfig) {
	*out = *in
	if in.Destination != nil {
		in, out := &in.Destination, &out.Destination
		*out = new(SnapshotDestination)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotGenerationConfig.
func (in *SnapshotGenerationConfig) DeepCopy() *SnapshotGenerationConfig {
	if in == nil {
		return nil
	}
	out := new(SnapshotGenerationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotSource) DeepCopyInto(out *SnapshotSource) {
	*out = *in
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(S3SnapshotSource)
		**out = **in
	}
	if in.StateSync != nil {
		in, out := &in.StateSync, &out.StateSync
		*out = new(StateSyncSource)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotSource.
func (in *SnapshotSource) DeepCopy() *SnapshotSource {
	if in == nil {
		return nil
	}
	out := new(SnapshotSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StateSyncSource) DeepCopyInto(out *StateSyncSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StateSyncSource.
func (in *StateSyncSource) DeepCopy() *StateSyncSource {
	if in == nil {
		return nil
	}
	out := new(StateSyncSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StaticPeerSource) DeepCopyInto(out *StaticPeerSource) {
	*out = *in
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StaticPeerSource.
func (in *StaticPeerSource) DeepCopy() *StaticPeerSource {
	if in == nil {
		return nil
	}
	out := new(StaticPeerSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageConfig) DeepCopyInto(out *StorageConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageConfig.
func (in *StorageConfig) DeepCopy() *StorageConfig {
	if in == nil {
		return nil
	}
	out := new(StorageConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskPlan) DeepCopyInto(out *TaskPlan) {
	*out = *in
	if in.Tasks != nil {
		in, out := &in.Tasks, &out.Tasks
		*out = make([]PlannedTask, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskPlan.
func (in *TaskPlan) DeepCopy() *TaskPlan {
	if in == nil {
		return nil
	}
	out := new(TaskPlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValidatorSpec) DeepCopyInto(out *ValidatorSpec) {
	*out = *in
	if in.Peers != nil {
		in, out := &in.Peers, &out.Peers
		*out = make([]PeerSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Snapshot != nil {
		in, out := &in.Snapshot, &out.Snapshot
		*out = new(SnapshotSource)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValidatorSpec.
func (in *ValidatorSpec) DeepCopy() *ValidatorSpec {
	if in == nil {
		return nil
	}
	out := new(ValidatorSpec)
	in.DeepCopyInto(out)
	return out
}
