//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArchiveSpec) DeepCopyInto(out *ArchiveSpec) {
	*out = *in
	if in.SnapshotGeneration != nil {
		in, out := &in.SnapshotGeneration, &out.SnapshotGeneration
		*out = new(SnapshotGenerationConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArchiveSpec.
func (in *ArchiveSpec) DeepCopy() *ArchiveSpec {
	if in == nil {
		return nil
	}
	out := new(ArchiveSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EC2TagsPeerSource) DeepCopyInto(out *EC2TagsPeerSource) {
	*out = *in
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EC2TagsPeerSource.
func (in *EC2TagsPeerSource) DeepCopy() *EC2TagsPeerSource {
	if in == nil {
		return nil
	}
	out := new(EC2TagsPeerSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EntrypointConfig) DeepCopyInto(out *EntrypointConfig) {
	*out = *in
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EntrypointConfig.
func (in *EntrypointConfig) DeepCopy() *EntrypointConfig {
	if in == nil {
		return nil
	}
	out := new(EntrypointConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FailedTaskInfo) DeepCopyInto(out *FailedTaskInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FailedTaskInfo.
func (in *FailedTaskInfo) DeepCopy() *FailedTaskInfo {
	if in == nil {
		return nil
	}
	out := new(FailedTaskInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ForkConfig) DeepCopyInto(out *ForkConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ForkConfig.
func (in *ForkConfig) DeepCopy() *ForkConfig {
	if in == nil {
		return nil
	}
	out := new(ForkConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FullNodeSpec) DeepCopyInto(out *FullNodeSpec) {
	*out = *in
	if in.Snapshot != nil {
		in, out := &in.Snapshot, &out.Snapshot
		*out = new(SnapshotSource)
		(*in).DeepCopyInto(*out)
	}
	if in.SnapshotGeneration != nil {
		in, out := &in.SnapshotGeneration, &out.SnapshotGeneration
		*out = new(SnapshotGenerationConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FullNodeSpec.
func (in *FullNodeSpec) DeepCopy() *FullNodeSpec {
	if in == nil {
		return nil
	}
	out := new(FullNodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenesisAccount) DeepCopyInto(out *GenesisAccount) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenesisAccount.
func (in *GenesisAccount) DeepCopy() *GenesisAccount {
	if in == nil {
		return nil
	}
	out := new(GenesisAccount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenesisCeremonyConfig) DeepCopyInto(out *GenesisCeremonyConfig) {
	*out = *in
	if in.Accounts != nil {
		in, out := &in.Accounts, &out.Accounts
		*out = make([]GenesisAccount, len(*in))
		copy(*out, *in)
	}
	if in.Overrides != nil {
		in, out := &in.Overrides, &out.Overrides
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.MaxCeremonyDuration != nil {
		in, out := &in.MaxCeremonyDuration, &out.MaxCeremonyDuration
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.Fork != nil {
		in, out := &in.Fork, &out.Fork
		*out = new(ForkConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenesisCeremonyConfig.
func (in *GenesisCeremonyConfig) DeepCopy() *GenesisCeremonyConfig {
	if in == nil {
		return nil
	}
	out := new(GenesisCeremonyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenesisCeremonyNodeConfig) DeepCopyInto(out *GenesisCeremonyNodeConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenesisCeremonyNodeConfig.
func (in *GenesisCeremonyNodeConfig) DeepCopy() *GenesisCeremonyNodeConfig {
	if in == nil {
		return nil
	}
	out := new(GenesisCeremonyNodeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupNodeStatus) DeepCopyInto(out *GroupNodeStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupNodeStatus.
func (in *GroupNodeStatus) DeepCopy() *GroupNodeStatus {
	if in == nil {
		return nil
	}
	out := new(GroupNodeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HardForkStrategy) DeepCopyInto(out *HardForkStrategy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HardForkStrategy.
func (in *HardForkStrategy) DeepCopy() *HardForkStrategy {
	if in == nil {
		return nil
	}
	out := new(HardForkStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InternalServicePorts) DeepCopyInto(out *InternalServicePorts) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InternalServicePorts.
func (in *InternalServicePorts) DeepCopy() *InternalServicePorts {
	if in == nil {
		return nil
	}
	out := new(InternalServicePorts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InternalServiceStatus) DeepCopyInto(out *InternalServiceStatus) {
	*out = *in
	out.Ports = in.Ports
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InternalServiceStatus.
func (in *InternalServiceStatus) DeepCopy() *InternalServiceStatus {
	if in == nil {
		return nil
	}
	out := new(InternalServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LabelPeerSource) DeepCopyInto(out *LabelPeerSource) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LabelPeerSource.
func (in *LabelPeerSource) DeepCopy() *LabelPeerSource {
	if in == nil {
		return nil
	}
	out := new(LabelPeerSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringConfig) DeepCopyInto(out *MonitoringConfig) {
	*out = *in
	if in.ServiceMonitor != nil {
		in, out := &in.ServiceMonitor, &out.ServiceMonitor
		*out = new(ServiceMonitorConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringConfig.
func (in *MonitoringConfig) DeepCopy() *MonitoringConfig {
	if in == nil {
		return nil
	}
	out := new(MonitoringConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkingConfig) DeepCopyInto(out *NetworkingConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkingConfig.
func (in *NetworkingConfig) DeepCopy() *NetworkingConfig {
	if in == nil {
		return nil
	}
	out := new(NetworkingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkingStatus) DeepCopyInto(out *NetworkingStatus) {
	*out = *in
	if in.Routes != nil {
		in, out := &in.Routes, &out.Routes
		*out = make([]RouteStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkingStatus.
func (in *NetworkingStatus) DeepCopy() *NetworkingStatus {
	if in == nil {
		return nil
	}
	out := new(NetworkingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PeerSource) DeepCopyInto(out *PeerSource) {
	*out = *in
	if in.EC2Tags != nil {
		in, out := &in.EC2Tags, &out.EC2Tags
		*out = new(EC2TagsPeerSource)
		(*in).DeepCopyInto(*out)
	}
	if in.Static != nil {
		in, out := &in.Static, &out.Static
		*out = new(StaticPeerSource)
		(*in).DeepCopyInto(*out)
	}
	if in.Label != nil {
		in, out := &in.Label, &out.Label
		*out = new(LabelPeerSource)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PeerSource.
func (in *PeerSource) DeepCopy() *PeerSource {
	if in == nil {
		return nil
	}
	out := new(PeerSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlannedTask) DeepCopyInto(out *PlannedTask) {
	*out = *in
	if in.Params != nil {
		in, out := &in.Params, &out.Params
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
	if in.SubmittedAt != nil {
		in, out := &in.SubmittedAt, &out.SubmittedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlannedTask.
func (in *PlannedTask) DeepCopy() *PlannedTask {
	if in == nil {
		return nil
	}
	out := new(PlannedTask)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplayerSpec) DeepCopyInto(out *ReplayerSpec) {
	*out = *in
	in.Snapshot.DeepCopyInto(&out.Snapshot)
	if in.ResultExport != nil {
		in, out := &in.ResultExport, &out.ResultExport
		*out = new(ResultExportConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplayerSpec.
func (in *ReplayerSpec) DeepCopy() *ReplayerSpec {
	if in == nil {
		return nil
	}
	out := new(ReplayerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResultExportConfig) DeepCopyInto(out *ResultExportConfig) {
	*out = *in
	if in.ShadowResult != nil {
		in, out := &in.ShadowResult, &out.ShadowResult
		*out = new(ShadowResultConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResultExportConfig.
func (in *ResultExportConfig) DeepCopy() *ResultExportConfig {
	if in == nil {
		return nil
	}
	out := new(ResultExportConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RolloutStatus) DeepCopyInto(out *RolloutStatus) {
	*out = *in
	in.StartedAt.DeepCopyInto(&out.StartedAt)
	if in.IncumbentNodes != nil {
		in, out := &in.IncumbentNodes, &out.IncumbentNodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.EntrantNodes != nil {
		in, out := &in.EntrantNodes, &out.EntrantNodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RolloutStatus.
func (in *RolloutStatus) DeepCopy() *RolloutStatus {
	if in == nil {
		return nil
	}
	out := new(RolloutStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouteStatus) DeepCopyInto(out *RouteStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouteStatus.
func (in *RouteStatus) DeepCopy() *RouteStatus {
	if in == nil {
		return nil
	}
	out := new(RouteStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3SnapshotSource) DeepCopyInto(out *S3SnapshotSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3SnapshotSource.
func (in *S3SnapshotSource) DeepCopy() *S3SnapshotSource {
	if in == nil {
		return nil
	}
	out := new(S3SnapshotSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeiNode) DeepCopyInto(out *SeiNode) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeiNode.
func (in *SeiNode) DeepCopy() *SeiNode {
	if in == nil {
		return nil
	}
	out := new(SeiNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SeiNode) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeiNodeDeployment) DeepCopyInto(out *SeiNodeDeployment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeiNodeDeployment.
func (in *SeiNodeDeployment) DeepCopy() *SeiNodeDeployment {
	if in == nil {
		return nil
	}
	out := new(SeiNodeDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SeiNodeDeployment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeiNodeDeploymentList) DeepCopyInto(out *SeiNodeDeploymentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SeiNodeDeployment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeiNodeDeploymentList.
func (in *SeiNodeDeploymentList) DeepCopy() *SeiNodeDeploymentList {
	if in == nil {
		return nil
	}
	out := new(SeiNodeDeploymentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SeiNodeDeploymentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeiNodeDeploymentSpec) DeepCopyInto(out *SeiNodeDeploymentSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
	if in.Genesis != nil {
		in, out := &in.Genesis, &out.Genesis
		*out = new(GenesisCeremonyConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Networking != nil {
		in, out := &in.Networking, &out.Networking
		*out = new(NetworkingConfig)
		**out = **in
	}
	if in.Monitoring != nil {
		in, out := &in.Monitoring, &out.Monitoring
		*out = new(MonitoringConfig)
		(*in).DeepCopyInto(*out)
	}
	in.UpdateStrategy.DeepCopyInto(&out.UpdateStrategy)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeiNodeDeploymentSpec.
func (in *SeiNodeDeploymentSpec) DeepCopy() *SeiNodeDeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(SeiNodeDeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeiNodeDeploymentStatus) DeepCopyInto(out *SeiNodeDeploymentStatus) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]GroupNodeStatus, len(*in))
		copy(*out, *in)
	}
	if in.Plan != nil {
		in, out := &in.Plan, &out.Plan
		*out = new(TaskPlan)
		(*in).DeepCopyInto(*out)
	}
	if in.IncumbentNodes != nil {
		in, out := &in.IncumbentNodes, &out.IncumbentNodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Rollout != nil {
		in, out := &in.Rollout, &out.Rollout
		*out = new(RolloutStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.NetworkingStatus != nil {
		in, out := &in.NetworkingStatus, &out.NetworkingStatus
		*out = new(NetworkingStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.InternalService != nil {
		in, out := &in.InternalService, &out.InternalService
		*out = new(InternalServiceStatus)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeiNodeDeploymentStatus.
func (in *SeiNodeDeploymentStatus) DeepCopy() *SeiNodeDeploymentStatus {
	if in == nil {
		return nil
	}
	out := new(SeiNodeDeploymentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeiNodeList) DeepCopyInto(out *SeiNodeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SeiNode, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeiNodeList.
func (in *SeiNodeList) DeepCopy() *SeiNodeList {
	if in == nil {
		return nil
	}
	out := new(SeiNodeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SeiNodeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeiNodeSpec) DeepCopyInto(out *SeiNodeSpec) {
	*out = *in
	if in.Peers != nil {
		in, out := &in.Peers, &out.Peers
		*out = make([]PeerSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Entrypoint != nil {
		in, out := &in.Entrypoint, &out.Entrypoint
		*out = new(EntrypointConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Overrides != nil {
		in, out := &in.Overrides, &out.Overrides
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Sidecar != nil {
		in, out := &in.Sidecar, &out.Sidecar
		*out = new(SidecarConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.PodLabels != nil {
		in, out := &in.PodLabels, &out.PodLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.FullNode != nil {
		in, out := &in.FullNode, &out.FullNode
		*out = new(FullNodeSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Archive != nil {
		in, out := &in.Archive, &out.Archive
		*out = new(ArchiveSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Replayer != nil {
		in, out := &in.Replayer, &out.Replayer
		*out = new(ReplayerSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Validator != nil {
		in, out := &in.Validator, &out.Validator
		*out = new(ValidatorSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeiNodeSpec.
func (in *SeiNodeSpec) DeepCopy() *SeiNodeSpec {
	if in == nil {
		return nil
	}
	out := new(SeiNodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeiNodeStatus) DeepCopyInto(out *SeiNodeStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PhaseTransitionTime != nil {
		in, out := &in.PhaseTransitionTime, &out.PhaseTransitionTime
		*out = (*in).DeepCopy()
	}
	if in.Plan != nil {
		in, out := &in.Plan, &out.Plan
		*out = new(TaskPlan)
		(*in).DeepCopyInto(*out)
	}
	if in.ResolvedPeers != nil {
		in, out := &in.ResolvedPeers, &out.ResolvedPeers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeiNodeStatus.
func (in *SeiNodeStatus) DeepCopy() *SeiNodeStatus {
	if in == nil {
		return nil
	}
	out := new(SeiNodeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeiNodeTemplate) DeepCopyInto(out *SeiNodeTemplate) {
	*out = *in
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = new(SeiNodeTemplateMeta)
		(*in).DeepCopyInto(*out)
	}
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeiNodeTemplate.
func (in *SeiNodeTemplate) DeepCopy() *SeiNodeTemplate {
	if in == nil {
		return nil
	}
	out := new(SeiNodeTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeiNodeTemplateMeta) DeepCopyInto(out *SeiNodeTemplateMeta) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeiNodeTemplateMeta.
func (in *SeiNodeTemplateMeta) DeepCopy() *SeiNodeTemplateMeta {
	if in == nil {
		return nil
	}
	out := new(SeiNodeTemplateMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceMonitorConfig) DeepCopyInto(out *ServiceMonitorConfig) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceMonitorConfig.
func (in *ServiceMonitorConfig) DeepCopy() *ServiceMonitorConfig {
	if in == nil {
		return nil
	}
	out := new(ServiceMonitorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShadowResultConfig) DeepCopyInto(out *ShadowResultConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShadowResultConfig.
func (in *ShadowResultConfig) DeepCopy() *ShadowResultConfig {
	if in == nil {
		return nil
	}
	out := new(ShadowResultConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SidecarConfig) DeepCopyInto(out *SidecarConfig) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SidecarConfig.
func (in *SidecarConfig) DeepCopy() *SidecarConfig {
	if in == nil {
		return nil
	}
	out := new(SidecarConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotGenerationConfig) DeepCopyInto(out *SnapshotGenerationConfig) {
	*out = *in
	if in.Tendermint != nil {
		in, out := &in.Tendermint, &out.Tendermint
		*out = new(TendermintSnapshotGenerationConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotGenerationConfig.
func (in *SnapshotGenerationConfig) DeepCopy() *SnapshotGenerationConfig {
	if in == nil {
		return nil
	}
	out := new(SnapshotGenerationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotSource) DeepCopyInto(out *SnapshotSource) {
	*out = *in
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(S3SnapshotSource)
		**out = **in
	}
	if in.StateSync != nil {
		in, out := &in.StateSync, &out.StateSync
		*out = new(StateSyncSource)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotSource.
func (in *SnapshotSource) DeepCopy() *SnapshotSource {
	if in == nil {
		return nil
	}
	out := new(SnapshotSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StateSyncSource) DeepCopyInto(out *StateSyncSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StateSyncSource.
func (in *StateSyncSource) DeepCopy() *StateSyncSource {
	if in == nil {
		return nil
	}
	out := new(StateSyncSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StaticPeerSource) DeepCopyInto(out *StaticPeerSource) {
	*out = *in
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StaticPeerSource.
func (in *StaticPeerSource) DeepCopy() *StaticPeerSource {
	if in == nil {
		return nil
	}
	out := new(StaticPeerSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskPlan) DeepCopyInto(out *TaskPlan) {
	*out = *in
	if in.Tasks != nil {
		in, out := &in.Tasks, &out.Tasks
		*out = make([]PlannedTask, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FailedTaskIndex != nil {
		in, out := &in.FailedTaskIndex, &out.FailedTaskIndex
		*out = new(int)
		**out = **in
	}
	if in.FailedTaskDetail != nil {
		in, out := &in.FailedTaskDetail, &out.FailedTaskDetail
		*out = new(FailedTaskInfo)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskPlan.
func (in *TaskPlan) DeepCopy() *TaskPlan {
	if in == nil {
		return nil
	}
	out := new(TaskPlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TendermintSnapshotGenerationConfig) DeepCopyInto(out *TendermintSnapshotGenerationConfig) {
	*out = *in
	if in.Publish != nil {
		in, out := &in.Publish, &out.Publish
		*out = new(TendermintSnapshotPublishConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TendermintSnapshotGenerationConfig.
func (in *TendermintSnapshotGenerationConfig) DeepCopy() *TendermintSnapshotGenerationConfig {
	if in == nil {
		return nil
	}
	out := new(TendermintSnapshotGenerationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TendermintSnapshotPublishConfig) DeepCopyInto(out *TendermintSnapshotPublishConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TendermintSnapshotPublishConfig.
func (in *TendermintSnapshotPublishConfig) DeepCopy() *TendermintSnapshotPublishConfig {
	if in == nil {
		return nil
	}
	out := new(TendermintSnapshotPublishConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdateStrategy) DeepCopyInto(out *UpdateStrategy) {
	*out = *in
	if in.HardFork != nil {
		in, out := &in.HardFork, &out.HardFork
		*out = new(HardForkStrategy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateStrategy.
func (in *UpdateStrategy) DeepCopy() *UpdateStrategy {
	if in == nil {
		return nil
	}
	out := new(UpdateStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValidatorSpec) DeepCopyInto(out *ValidatorSpec) {
	*out = *in
	if in.Snapshot != nil {
		in, out := &in.Snapshot, &out.Snapshot
		*out = new(SnapshotSource)
		(*in).DeepCopyInto(*out)
	}
	if in.GenesisCeremony != nil {
		in, out := &in.GenesisCeremony, &out.GenesisCeremony
		*out = new(GenesisCeremonyNodeConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValidatorSpec.
func (in *ValidatorSpec) DeepCopy() *ValidatorSpec {
	if in == nil {
		return nil
	}
	out := new(ValidatorSpec)
	in.DeepCopyInto(out)
	return out
}
