apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../default
  - ../../efs
images:
  - name: controller
    newName: 189176372795.dkr.ecr.us-east-2.amazonaws.com/sei/sei-node-controller
    newTag: latest
patches:
  - path: manager_patch.yaml
    target:
      kind: Deployment
