apiVersion: sei.io/v1alpha1
kind: SeiNode
metadata:
  name: pacific-1-snapshotter
  namespace: default
spec:
  chainId: pacific-1
  mode: full
  image: 189176372795.dkr.ecr.us-east-2.amazonaws.com/sei/sei-chain:837ba922db3f5313a474fbe0c7bba4cbec466cdc

  sidecar:
    image: ghcr.io/sei-protocol/seictl@sha256:bdd1861e4d0803b5318fee649b781edb814ed845779b1433a8a7ebf6f856e907

  entrypoint:
    command: ["seid"]
    args: ["start", "--home", "/sei"]

  genesis:
    chainId: pacific-1
    s3:
      uri: s3://sei-testnet-genesis-config/pacific-1/genesis.json
      region: us-east-2

  peers:
    sources:
      - ec2Tags:
          region: eu-central-1
          tags:
            ChainIdentifier: pacific-1
            Component: snapshotter

  stateSync:
    trustPeriod: "9999h0m0s"
    backfillBlocks: 0
    snapshot:
      bucket:
        uri: s3://pacific-1-snapshots/state-sync/
      region: eu-central-1

  storage:
    retainOnDelete: true

  snapshotGeneration:
    keepRecent: 5
    destination:
      s3:
        bucket: sei-node-mvp
        prefix: snapshot/
        region: eu-central-1
