apiVersion: sei.io/v1alpha1
kind: SeiNode
metadata:
  name: pacific-1-replay
  namespace: default
spec:
  chainId: pacific-1
  mode: archive
  image: 189176372795.dkr.ecr.us-east-2.amazonaws.com/sei/sei-chain:837ba922db3f5313a474fbe0c7bba4cbec466cdc

  sidecar:
    image: ghcr.io/sei-protocol/seictl@sha256:f47f680d220b191e4934343819923b0501b9dd72f2b5c315782a524efc7b8a1b

  entrypoint:
    command: ["seid"]
    args: ["start", "--home", "/sei"]

  genesis:
    chainId: pacific-1
    s3:
      uri: s3://sei-testnet-genesis-config/pacific-1/genesis.json
      region: us-east-2

  peers:
    sources:
      - ec2Tags:
          region: eu-central-1
          tags:
            ChainIdentifier: pacific-1
            Component: snapshotter

  stateSync:
    trustPeriod: "9999h0m0s"
    backfillBlocks: 0
    snapshot:
      bucket:
        uri: s3://pacific-1-snapshots/state-sync/
      region: eu-central-1

  storage:
    retainOnDelete: true
